@file:Suppress("MagicNumber")

package com.masselis.tpmsadvanced.core.ui

import androidx.compose.ui.graphics.Color
import com.masselis.tpmsadvanced.core.common.appContext


public val md_theme_light_primary: Color = Color(0xFF0E6E14)
public val md_theme_light_onPrimary: Color = Color(0xFFFFFFFF)
public val md_theme_light_primaryContainer: Color = Color(0xFF9CF88D)
public val md_theme_light_onPrimaryContainer: Color = Color(0xFF002201)
public val md_theme_light_secondary: Color = Color(0xFF53634E)
public val md_theme_light_onSecondary: Color = Color(0xFFFFFFFF)
public val md_theme_light_secondaryContainer: Color = Color(0xFFD6E8CD)
public val md_theme_light_onSecondaryContainer: Color = Color(0xFF111F0F)
public val md_theme_light_tertiary: Color = Color(0xFF386569)
public val md_theme_light_onTertiary: Color = Color(0xFFFFFFFF)
public val md_theme_light_tertiaryContainer: Color = Color(0xFFBCEBEF)
public val md_theme_light_onTertiaryContainer: Color = Color(0xFF002022)
public val md_theme_light_error: Color = Color(0xFFBA1A1A)
public val md_theme_light_errorContainer: Color = Color(0xFFFFDAD6)
public val md_theme_light_onError: Color = Color(0xFFFFFFFF)
public val md_theme_light_onErrorContainer: Color = Color(0xFF410002)
public val md_theme_light_background: Color = Color(0xFFFCFDF6)
public val md_theme_light_onBackground: Color = Color(0xFF1A1C19)
public val md_theme_light_surface: Color =
    Color(appContext.getColor(R.color.md_theme_light_surface))
public val md_theme_light_onSurface: Color = Color(0xFF1A1C19)
public val md_theme_light_surfaceVariant: Color = Color(0xFFDFE4D8)
public val md_theme_light_onSurfaceVariant: Color = Color(0xFF42493F)
public val md_theme_light_outline: Color = Color(0xFF73796E)
public val md_theme_light_inverseOnSurface: Color = Color(0xFFF1F1EB)
public val md_theme_light_inverseSurface: Color = Color(0xFF2F312D)
public val md_theme_light_inversePrimary: Color = Color(0xFF81DB74)
public val md_theme_light_shadow: Color = Color(0xFF000000)
public val md_theme_light_surfaceTint: Color = Color(0xFF0E6E14)
public val md_theme_light_surfaceTintColor: Color = Color(0xFF0E6E14)

public val md_theme_dark_primary: Color = Color(0xFF81DB74)
public val md_theme_dark_onPrimary: Color = Color(0xFF003A04)
public val md_theme_dark_primaryContainer: Color = Color(0xFF005308)
public val md_theme_dark_onPrimaryContainer: Color = Color(0xFF9CF88D)
public val md_theme_dark_secondary: Color = Color(0xFFBACCB2)
public val md_theme_dark_onSecondary: Color = Color(0xFF263422)
public val md_theme_dark_secondaryContainer: Color = Color(0xFF3C4B37)
public val md_theme_dark_onSecondaryContainer: Color = Color(0xFFD6E8CD)
public val md_theme_dark_tertiary: Color = Color(0xFFA0CFD3)
public val md_theme_dark_onTertiary: Color = Color(0xFF00363A)
public val md_theme_dark_tertiaryContainer: Color = Color(0xFF1E4D51)
public val md_theme_dark_onTertiaryContainer: Color = Color(0xFFBCEBEF)
public val md_theme_dark_error: Color = Color(0xFFFFB4AB)
public val md_theme_dark_errorContainer: Color = Color(0xFF93000A)
public val md_theme_dark_onError: Color = Color(0xFF690005)
public val md_theme_dark_onErrorContainer: Color = Color(0xFFFFDAD6)
public val md_theme_dark_background: Color = Color(0xFF1A1C19)
public val md_theme_dark_onBackground: Color = Color(0xFFE2E3DD)
public val md_theme_dark_surface: Color = Color(appContext.getColor(R.color.md_theme_dark_surface))
public val md_theme_dark_onSurface: Color = Color(0xFFE2E3DD)
public val md_theme_dark_surfaceVariant: Color = Color(0xFF42493F)
public val md_theme_dark_onSurfaceVariant: Color = Color(0xFFC2C8BC)
public val md_theme_dark_outline: Color = Color(0xFF8C9388)
public val md_theme_dark_inverseOnSurface: Color = Color(0xFF1A1C19)
public val md_theme_dark_inverseSurface: Color = Color(0xFFE2E3DD)
public val md_theme_dark_inversePrimary: Color = Color(0xFF0E6E14)
public val md_theme_dark_shadow: Color = Color(0xFF000000)
public val md_theme_dark_surfaceTint: Color = Color(0xFF81DB74)
public val md_theme_dark_surfaceTintColor: Color = Color(0xFF81DB74)


public val seed: Color = Color(0xFF5FB755)
