name: Setup project and android
description: Specific steps to checkout the project and setup the environment
runs:
  using: "composite"
  steps:
    - name: Initialization scripts
      id: initialization_scripts
      shell: bash
      run: |
        # Enable KVM group perms
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
        
        # Free some space on the current runner to allow installation of bigger emulators
        # Copy/paste from https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        
        # Read the expected emulator package
        # Inspired by https://github.com/amyu/setup-android?tab=readme-ov-file#usage
        package=`perl -nlE 'say if s/garunner-emulator \= \"(.*)\"/$1/g' gradle/libs.versions.toml`
        echo "emulatorPackage=$package" >> $GITHUB_OUTPUT

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v3
      with:
        log-accepted-android-sdk-licenses: false # Cleans the log output

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3