name: Setup project and android
description: Specific steps to checkout the project and setup the environment
runs:
  using: "composite"
  steps:
    - name: Initialization scripts
      id: initialization_scripts
      shell: bash
      run: |
        # Enable KVM group perms
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
        
        # Free some space on the current runner to allow installation of bigger emulators
        # Copy/paste from https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        
        # Read the expected emulator package
        # Inspired by https://github.com/amyu/setup-android?tab=readme-ov-file#usage
        package=`perl -nlE 'say if s/garunner-emulator \= \"(.*)\"/$1/g' gradle/libs.versions.toml`
        echo "emulatorPackage=$package" >> $GITHUB_OUTPUT

    # This JDK is downloaded because Gradle needs a basic java environment to start before
    # downloading its own JDK distribution and also because some tools used by
    # "android-actions/setup-android" need a JVM.
    - name: Set up bootstrap JDK
      uses: actions/setup-java@v6
      with:
        distribution: temurin
        # JDK used by Gradle to run on is always fetch from gradle-daemon-jvm.properties.
        # JDK used to compile code is automatically fetch by plugin "org.gradle.toolchains.foojay-resolver-convention"
        # but if the current machine already have JDK 21 installed, the compiler reuses it.
        java-version: 21

    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v4
      with:
        log-accepted-android-sdk-licenses: false # Cleans the log output

    - name: Install Bitwarden CLI
      shell: bash
      run: npm install -g @bitwarden/cli@2026.6.0

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
