name: Setup project and android
description: Specific steps to checkout the project and setup the environment
runs:
  using: "composite"
  steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8

    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v2