package com.masselis.tpmsadvanced.interfaces.composable

import androidx.compose.ui.graphics.Color
import com.masselis.tpmsadvanced.R
import com.masselis.tpmsadvanced.common.appContext

internal val md_theme_light_primary = Color(0xFF0E6E14)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFF9CF88D)
internal val md_theme_light_onPrimaryContainer = Color(0xFF002201)
internal val md_theme_light_secondary = Color(0xFF53634E)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFD6E8CD)
internal val md_theme_light_onSecondaryContainer = Color(0xFF111F0F)
internal val md_theme_light_tertiary = Color(0xFF386569)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFBCEBEF)
internal val md_theme_light_onTertiaryContainer = Color(0xFF002022)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color(0xFFFCFDF6)
internal val md_theme_light_onBackground = Color(0xFF1A1C19)
internal val md_theme_light_surface = Color(appContext.getColor(R.color.md_theme_light_surface))
internal val md_theme_light_onSurface = Color(0xFF1A1C19)
internal val md_theme_light_surfaceVariant = Color(0xFFDFE4D8)
internal val md_theme_light_onSurfaceVariant = Color(0xFF42493F)
internal val md_theme_light_outline = Color(0xFF73796E)
internal val md_theme_light_inverseOnSurface = Color(0xFFF1F1EB)
internal val md_theme_light_inverseSurface = Color(0xFF2F312D)
internal val md_theme_light_inversePrimary = Color(0xFF81DB74)
internal val md_theme_light_shadow = Color(0xFF000000)
internal val md_theme_light_surfaceTint = Color(0xFF0E6E14)
internal val md_theme_light_surfaceTintColor = Color(0xFF0E6E14)

internal val md_theme_dark_primary = Color(0xFF81DB74)
internal val md_theme_dark_onPrimary = Color(0xFF003A04)
internal val md_theme_dark_primaryContainer = Color(0xFF005308)
internal val md_theme_dark_onPrimaryContainer = Color(0xFF9CF88D)
internal val md_theme_dark_secondary = Color(0xFFBACCB2)
internal val md_theme_dark_onSecondary = Color(0xFF263422)
internal val md_theme_dark_secondaryContainer = Color(0xFF3C4B37)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFD6E8CD)
internal val md_theme_dark_tertiary = Color(0xFFA0CFD3)
internal val md_theme_dark_onTertiary = Color(0xFF00363A)
internal val md_theme_dark_tertiaryContainer = Color(0xFF1E4D51)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFBCEBEF)
internal val md_theme_dark_error = Color(0xFFFFB4AB)
internal val md_theme_dark_errorContainer = Color(0xFF93000A)
internal val md_theme_dark_onError = Color(0xFF690005)
internal val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_background = Color(0xFF1A1C19)
internal val md_theme_dark_onBackground = Color(0xFFE2E3DD)
internal val md_theme_dark_surface = Color(appContext.getColor(R.color.md_theme_dark_surface))
internal val md_theme_dark_onSurface = Color(0xFFE2E3DD)
internal val md_theme_dark_surfaceVariant = Color(0xFF42493F)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFC2C8BC)
internal val md_theme_dark_outline = Color(0xFF8C9388)
internal val md_theme_dark_inverseOnSurface = Color(0xFF1A1C19)
internal val md_theme_dark_inverseSurface = Color(0xFFE2E3DD)
internal val md_theme_dark_inversePrimary = Color(0xFF0E6E14)
internal val md_theme_dark_shadow = Color(0xFF000000)
internal val md_theme_dark_surfaceTint = Color(0xFF81DB74)
internal val md_theme_dark_surfaceTintColor = Color(0xFF81DB74)


internal val seed = Color(0xFF5FB755)
