naming:
  FunctionNaming:
    ignoreAnnotated:
      - 'Composable'
style:
  UnnecessaryAbstractClass:
    ignoreAnnotated:
      - 'Component'
  MagicNumber:
    ignoreAnnotated:
      - 'Composable'
  DestructuringDeclarationWithTooManyEntries:
    # I disagree with https://detekt.dev/docs/rules/style/#destructuringdeclarationwithtoomanyentries
    maxDestructuringEntries: 10
complexity:
  LongParameterList:
    functionThreshold: 10
