name: Run on emulator
description: Starts the emulator and run the filled script
inputs:
  script:
    description: Script to run once the emulator is ready
    required: true
runs:
  using: "composite"
  steps:
    - name: Starts emulator
      shell: bash
      run: |
        #!/usr/bin/env bash

        brew install intel-haxm android-commandlinetools android-platform-tools
        
        # Install AVD files
        echo "y" | sdkmanager --install 'system-images;android-27;default;x86_64'

        # Create emulator
        echo "no" | avdmanager create avd -n android_emulator -d 19 --package 'system-images;android-27;default;x86_64'
        
        # list emulator
        echo "Available emulator"
        $ANDROID_HOME/emulator/emulator -list-avds

        if false; then
        emulator_config=~/.android/avd/android_emulator.avd/config.ini
        # The following is to support empty OR populated config.ini files,
        # the state of which is dependant on the version of the emulator used (which we don't control),
        # Replace existing config (NOTE we're on MacOS so sed works differently!)
        sed -i .bak 's/hw.lcd.density=.*/hw.lcd.density=420/' "$emulator_config"
        sed -i .bak 's/hw.lcd.height=.*/hw.lcd.height=1920/' "$emulator_config"
        sed -i .bak 's/hw.lcd.width=.*/hw.lcd.width=1080/' "$emulator_config"
        # Or, add new config
        if ! grep -q "hw.lcd.density" "$emulator_config"; then
        echo "hw.lcd.density=420" >> "$emulator_config"
        fi
        if ! grep -q "hw.lcd.height" "$emulator_config"; then
        echo "hw.lcd.height=1920" >> "$emulator_config"
        fi
        if ! grep -q "hw.lcd.width" "$emulator_config"; then
        echo "hw.lcd.width=1080" >> "$emulator_config"
        fi
        echo "Emulator settings ($emulator_config)"
        cat "$emulator_config"
        fi

        echo "Starting emulator"

        # Start emulator in background
        nohup $ANDROID_HOME/emulator/emulator -avd android_emulator -no-snapshot -no-audio -gpu host -no-boot-anim -qemu -m 2048 > /dev/null 2>&1 &

        echo "Emulator starting"

    - name: Run script
      shell: bash
      run: |
        ${{ inputs.script }}