name: Unlock with git-crypt on macos
description: Specific git-crypt shell commands for macos
inputs:
  git_crypt_key:
    description: Key used to unlock secret files
    required: true
runs:
  using: "composite"
  steps:
    - name: Unlock with git-crypt
      shell: bash
      run: |
        brew install git-crypt
        echo ${{ inputs.git_crypt_key }} | base64 --decode > ~/key.key
        git stash
        git-crypt unlock ~/key.key
        rm ~/key.key