name: Beta

on:
  push:
    branches:
      - release/*

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  publication:
    name: Publish to beta
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Publish to beta and create a github release
        env:
          BITWARDEN_SERVER: self-hosted
          BITWARDEN_SELF_HOSTED_URL: ${{ secrets.BITWARDEN_SELF_HOSTED_URL }}
          BITWARDEN_EMAIL: ${{ secrets.BITWARDEN_CI_EMAIL }}
          BITWARDEN_PASSWORD: ${{ secrets.BITWARDEN_CI_PASSWORD }}
        run: >
          ./gradlew
          assertReleaseBranchIsValid
          build
          verifyPaparazzi
          createGithubPreRelease
          publishToPlayStoreBetaNormalRelease
          --stacktrace
