name: Beta

on:
  push:
    branches:
      - release/*

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  publication:
    name: Publish to beta
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Unlock secret
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Publish to beta and create a github release
        run: >
          ./gradlew
          assertReleaseBranchIsValid
          createGithubReleaseNormalRelease
          publishToPlayStoreBetaNormalRelease
