name: Beta

on:
  push:
    branches:
      - release/*

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  publication:
    name: Publish to beta
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - uses: ./.github/download_secrets/setup

      - name: Publish to beta and create a github release
        run: >
          ./gradlew
          assertReleaseBranchIsValid
          build
          verifyPaparazzi
          createGithubPreRelease
          publishToPlayStoreBetaNormalRelease
          --stacktrace
