name: Develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    name: Build everything, test and report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Analyse code, build and test everything
        run: >
          ./gradlew
          build
          verifyPaparazzi
          connectedDemoDebugAndroidTest
          copyScreenshot
          --scan

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "**/build/test-results/**/*.xml"

      - name: Lint reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Lint-reports
          path: "**/build/reports/lint-*.html"

      - name: Detekt reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Detekt-reports
          path: "**/build/reports/detekt/*.html"

      - name: Paparazzi failures screens
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Paparazzi-failures
          path: "**/build/paparazzi/failures/*.png"

      - name: Instrumented tests reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Instrumented-reports
          path: "**/build/reports/androidTests/**/*.html"

      - name: Screenshots report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Screenshots-reports
          path: "**/graphics/phone-screenshots/*.png"

      - name: APKs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: APKs
          path: "**/build/outputs/apk/**/*.apk"

      - name: Emulator logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Emulator-logs
          path: "build/emulator/*.txt"
