name: Develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build everything, test and report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Build everything and run unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --scan

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          junit_files: "**/build/test-results/**/*.xml"

      - name: Lint reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Lint-reports
          path: "**/build/reports/lint-*.html"

      - name: Detekt reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Detekt-reports
          path: "**/build/reports/detekt/*.html"

  instrumented_test_n_screenshots:
    name: Run instrumented tests and take screenshots
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Run androidTest + take screenshots
        uses: ./.github/actions/run-emulator
        with:
          script: ./gradlew connectedDemoDebugAndroidTest copyScreenshot

      - name: Instrumented tests reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Instrumented-reports
          path: "**/build/reports/androidTests/**/*.html"

      - name: Screenshots report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Screenshots-reports
          path: "**/graphics/phone-screenshots/*.png"
