name: Hotfix

on:
  push:
    branches:
      - hotfix/*

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build everything, test and report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Unlock secret
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Build everything and run unit tests
        run: >
          ./gradlew
          assertHotfixBranchIsValid
          build
          verifyPaparazzi

