name: Main production

on:
  push:
    tags:
      - production

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  promotion:
    name: Promote to production
    runs-on: macos-14
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - uses: ./.github/actions/git-crypt-macos
        with:
          git_crypt_key: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Promotes the github release, promotes from the beta channel to production, updates the screenshots
        uses: ./.github/actions/run-emulator
        with:
          script: ./gradlew promoteGithubReleaseNormalRelease updatePlayStoreScreenshotsNormalRelease promoteToPlayStoreProductionNormalRelease
