name: Main

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  publication:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Unlock secret
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2

      - name: Upload release
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bundle publishApps # Calling "publishApps" doesn't upload the mapping.txt file to crashlytics, to fix that, I've added "bundle"