name: Main production

on:
  push:
    tags:
      - production

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  promotion:
    name: Promote to production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Unlock secret
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2

      - name: Promotion
        uses: gradle/gradle-build-action@v2
        with:
          arguments: promoteArtifact

  screenshots_update:
    name: Updates play store screenshots
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Unlock with git-crypt
        run: |
          brew install git-crypt
          echo ${{ secrets.GIT_CRYPT_KEY }} | base64 --decode > ~/key.key
          git stash
          git-crypt unlock ~/key.key
          rm ~/key.key

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-31

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Update screenshots
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew publishListing
