name: Main production

on:
  push:
    tags:
      - production

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Promote to production
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Unlock with git-crypt
        run: |
          brew install git-crypt
          echo ${{ secrets.GIT_CRYPT_KEY }} | base64 --decode > ~/key.key
          git stash
          git-crypt unlock ~/key.key
          rm ~/key.key

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2

      - name: Promotion
        uses: gradle/gradle-build-action@v2
        with:
          arguments: promoteArtifact # This task cannot run simultaneously with publishListing because of concurrent issues when working with the play store (take a look at https://github.com/VincentMasselis/TPMS-advanced/actions/runs/3098953629/jobs/5017497505)

      - name: Update screenshots
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: 'x86_64'
          script: ./gradlew publishListing